In [4]:
import os
import sys
import pandas as pd
import numpy as np

sys.path.append(os.path.abspath('..'))

from config import DATA_DIR,RAW_DATA_PATH

In [10]:
df = pd.read_csv(RAW_DATA_PATH,encoding='latin1')

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [14]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [15]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [16]:
df = df.dropna(subset=["CustomerID"],axis=0)

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

df = df[(df["Quantity"]>0) & (df["UnitPrice"]>0)]

In [17]:
df.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  397884.000000                      397884  397884.000000  397884.000000
mean       12.988238  2011-07-10 23:41:23.511023       3.116488   15294.423453
min         1.000000         2010-12-01 08:26:00       0.001000   12346.000000
25%         2.000000         2011-04-07 11:12:00       1.250000   13969.000000
50%         6.000000         2011-07-31 14:39:00       1.950000   15159.000000
75%        12.000000         2011-10-20 14:33:00       3.750000   16795.000000
max     80995.000000         2011-12-09 12:50:00    8142.750000   18287.000000
std       179.331775                         NaN      22.097877    1713.141560